<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-25 13:01
=======
# Generated by Django 6.0.5 on 2026-05-20 05:56
>>>>>>> 8c05e676f9e5f713ad213e0a46b3f92e73af6c4d

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('loyalty', 'Loyalty Points'), ('mixed', 'Mixed Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_transaction_id', models.CharField(blank=True, max_length=100)),
                ('points_used', models.IntegerField(default=0, help_text='Loyalty points used for this payment')),
                ('reference_number', models.CharField(blank=True, help_text='External reference', max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('receipt_html', models.TextField(blank=True, help_text='HTML version for email')),
                ('receipt_text', models.TextField(blank=True, help_text='Text version for printing')),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(editable=False, help_text='Human-readable sale number (e.g., INV-20241215-0001)', max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending Payment'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('voided', 'Voided')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Fully Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid'), ('overpaid', 'Overpaid')], db_index=True, default='unpaid', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before tax and discount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount (e.g., VAT 16%)', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Tax rate applied to items', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total = subtotal - discount + tax', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid by customer', max_digits=12)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change to return to customer', max_digits=12)),
                ('loyalty_points_earned', models.IntegerField(default=0)),
                ('loyalty_points_redeemed', models.IntegerField(default=0)),
                ('loyalty_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount from loyalty points', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Sale notes (e.g., special instructions)')),
                ('void_reason', models.TextField(blank=True, help_text='Reason if sale is voided/cancelled')),
                ('sale_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False, help_text='Has this item been returned?')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_name', models.CharField(help_text='Product name at time of sale', max_length=200)),
                ('product_sku', models.CharField(help_text='Product SKU at time of sale', max_length=100)),
                ('product_barcode', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale', max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='unit_price × quantity', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='subtotal - discount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
