<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-25 13:01
=======
# Generated by Django 6.0.5 on 2026-05-20 05:56
>>>>>>> 8c05e676f9e5f713ad213e0a46b3f92e73af6c4d

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('description', models.TextField()),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('expense_date', models.DateField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name (e.g., Main Store Paybill)', max_length=100)),
                ('business_type', models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Till Number')], max_length=10)),
                ('shortcode', models.CharField(help_text='Paybill or Till number', max_length=10)),
                ('passkey', models.CharField(help_text='API Passkey from Daraja portal', max_length=100)),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('callback_url', models.URLField(help_text='URL for transaction callbacks')),
                ('timeout_url', models.URLField(help_text='URL for timeout callbacks')),
                ('result_url', models.URLField(help_text='URL for result callbacks (for B2C)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_shortcode', models.CharField(blank=True, help_text='Shortcode for receipts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(db_index=True, unique=True)),
                ('mpesa_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mpesa_total_count', models.IntegerField(default=0)),
                ('system_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('system_total_count', models.IntegerField(default=0)),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discrepancy_count', models.IntegerField(default=0)),
                ('unmatched_from_mpesa', models.JSONField(default=list)),
                ('unmatched_from_system', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('matched', 'All Matched'), ('discrepancy', 'Has Discrepancies'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('c2b', 'Customer to Business (Payment)'), ('b2c', 'Business to Customer (Refund/Withdrawal)'), ('stk_push', 'STK Push (Lipa Na M-Pesa)'), ('reversal', 'Transaction Reversal')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('phone_number', models.CharField(db_index=True, help_text='Customer M-Pesa phone number', max_length=15)),
                ('account_reference', models.CharField(help_text='Account reference (e.g., Invoice number)', max_length=50)),
                ('transaction_desc', models.CharField(blank=True, max_length=100)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_description', models.CharField(blank=True, max_length=200)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=500)),
                ('raw_request', models.JSONField(blank=True, default=dict, help_text='Raw request sent to M-Pesa')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw response from M-Pesa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name (e.g., Main Cash Register)', max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash Register'), ('mpesa', 'M-Pesa Paybill/Till'), ('bank', 'Bank Account'), ('mobile_money', 'Other Mobile Money'), ('credit', 'Customer Credit Account'), ('petty_cash', 'Petty Cash')], max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='Account number or reference', max_length=100)),
                ('mpesa_shortcode', models.CharField(blank=True, help_text='Paybill or Till number', max_length=20)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20)),
                ('mpesa_till', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20)),
                ('bank_swift_code', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at start of financial period', max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available balance', max_digits=15)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alert when balance falls below this', max_digits=15)),
                ('maximum_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed balance', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default account for this type')),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(db_index=True)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('unreconciled_transactions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('partial', 'Partially Reconciled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, help_text='Unique transaction reference number', max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale Payment'), ('refund', 'Refund to Customer'), ('supplier_payment', 'Supplier Payment'), ('expense', 'Expense'), ('salary', 'Salary Payment'), ('transfer', 'Account Transfer'), ('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal'), ('purchase', 'Purchase Payment'), ('return_refund', 'Supplier Return Refund')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Store Credit'), ('loyalty', 'Loyalty Points'), ('mixed', 'Mixed Payment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction fee (e.g., M-Pesa charges)', max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax on transaction', max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Amount - fee - tax', max_digits=15)),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='External reference (cheque number, M-Pesa code, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
