# Generated by Django 6.0.5 on 2026-05-25 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='payments.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory'),
        ),
        migrations.AddField(
            model_name='mpesareconciliation',
            name='mpesa_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payments.mpesaaccount'),
        ),
        migrations.AddField(
            model_name='mpesareconciliation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.mpesaaccount'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='mpesacallbacklog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_logs', to='payments.mpesatransaction'),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='cashier_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesaaccount',
            name='payment_account',
            field=models.OneToOneField(blank=True, help_text='Linked payment account for reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_config', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='from_account',
            field=models.ForeignKey(blank=True, help_text='Source account (money coming FROM)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='Destination account (money going TO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='payments.paymenttransaction'),
        ),
        migrations.AddIndex(
            model_name='mpesareconciliation',
            index=models.Index(fields=['reconciliation_date', 'status'], name='payments_mp_reconci_8f9d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['result_code'], name='payments_mp_result__d9bd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['created_at'], name='payments_mp_created_96686a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='payments_pa_account_bdb8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['name'], name='payments_pa_name_fa7dce_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['mpesa_shortcode'], name='payments_pa_mpesa_s_aa2d12_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['shortcode'], name='payments_mp_shortco_b1282f_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['environment'], name='payments_mp_environ_b96097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentreconciliation',
            unique_together={('reconciliation_date', 'account')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_c1fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='payments_pa_transac_be57c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_number'], name='payments_pa_referen_0a520a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['sale'], name='payments_pa_sale_id_5a316b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['customer'], name='payments_pa_custome_5e945b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date'], name='payments_pa_transac_2ad7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='payments_mp_merchan_da2348_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_3e414a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number'], name='payments_mp_phone_n_3895b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status'], name='payments_mp_status_dfa634_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['created_at'], name='payments_mp_created_78d6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_number'], name='payments_ex_expense_85bb53_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='payments_ex_status_e97550_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='payments_ex_expense_d51e3e_idx'),
        ),
    ]
